### ISSUE TITLE
Add fully static build

### ISSUE THREAD

**Issue by CajuM** [anuvu/stacker#47]
This is useful as a Linux distribution independent deployment method. It is also agnostic of package managers such as dpkg, snap, etc. And also of libraries present on the system.

**Comment by tych0** [comment]
I experimented with this a while ago and ran into a problem with a glibc + liblxc interaction where things just hung.

The problem was that setuid() in linux doesn't synchronize across threads, even though POSIX says it should. glibc tries to fix this up, but does it incorrectly for threads that are created via its clone() wrapper causing a hang.

I never resolved the issue, mostly posting this in case anyone tries it again. It would be a useful thing to have...
